Repository openstax/rex-web, pull requests merged in 2019-07, with the labels that each got.

#194 chore: add set -e to top of search build script
  script/build-search-client.bash
Labels: kd-maint

#172 Test attribution status in new page
  pytest-selenium/pages/base.py
  pytest-selenium/pages/content.py
  pytest-selenium/regions/base.py
  pytest-selenium/tests/test_attribution.py
Labels: kd-reading-exp

#211 add lcov for codecov
  package.json
Labels: kd-maint

#203 extend domVisitor to support multiple audit logics
  script/audits/crossBookLinks.ts
  script/audits/tooWideContent.ts
  script/domVisitor.ts
Labels: kd-maint

#202 Fix scrolling
  src/app/components/MainContent.tsx
  src/app/components/SkipToContentWrapper.tsx
  src/app/content/__image_snapshots__/genericstyles-screenshotspec-ts-content-looks-right-1-snap.png
  src/app/content/__image_snapshots__/genericstyles-screenshotspec-ts-content-looks-right-on-mobile-1-snap.png
  src/app/content/components/Attribution.spec.tsx
  src/app/content/components/Attribution.tsx
  src/app/content/components/Content.browserspec.tsx
  src/app/content/components/Content.tsx
  src/app/content/components/ContentPane.tsx
  src/app/content/components/Page.spec.tsx
  src/app/content/components/Page.tsx
  src/app/content/components/__snapshots__/Content.spec.tsx.snap
  src/app/content/components/utils/allImagesLoaded.spec.ts
  src/app/content/components/utils/allImagesLoaded.ts
  src/app/context/SkipToContent.ts
  src/app/utils.spec.ts
  src/app/utils.ts
  src/helpers/scrollTo.ts
  src/index.css
  src/test/fixtures/contents/testbook1-shortid:testpage12-shortid
Labels: bug

#193 feat: add sentry and redux-sentry-middleware
  package.json
  src/app/index.spec.tsx
  src/app/index.tsx
  src/config.d.ts
  src/config.development.js
  src/config.js
  src/config.test.js
  src/helpers/Sentry.spec.ts
  src/helpers/Sentry.ts
  yarn.lock
Labels: kd-reading-exp

#220 chore: upgrade nodejs
  .nvmrc
Labels: kd-maint

#199 ToC disables interacting with content on mobile
  pytest-selenium/pages/base.py
  pytest-selenium/pages/content.py
  pytest-selenium/tests/conftest.py
  pytest-selenium/tests/markers.py
  pytest-selenium/tests/test_toc.py
Labels: kd-reading-exp
