Repository openstax/rex-web, pull requests merged in 2020-01, with the labels that each got.

#404 Fire clearSearchHook conditionally also on openToc
  src/app/content/search/hooks/index.ts
Labels: bug

#400 Unclickable logo on mobile
  src/app/components/NavBar/__snapshots__/index.spec.tsx.snap
  src/app/components/NavBar/index.tsx
Labels: bug

#402 Fixed ctrl click not opening in a new tab
  src/app/content/components/ContentLink.tsx
Labels: bug

#413 Highlight notes - edit and delete
  src/app/components/Dropdown.tsx
  src/app/components/__snapshots__/Dropdown.spec.tsx.snap
  src/app/content/highlights/components/DisplayNote.tsx
  src/app/content/highlights/components/__snapshots__/DisplayNote.spec.tsx.snap
Labels: WIP

#412 Fixed menu offset
  src/app/components/NavBar/__snapshots__/index.spec.tsx.snap
  src/app/components/NavBar/styled.tsx
Labels: bug, dev-approved

#411 Remove scroll on login nudge
  src/app/content/highlights/components/Confirmation.tsx
  src/app/content/highlights/components/__snapshots__/Confirmation.spec.tsx.snap
Labels: bug, dev-approved

#429 Inline highlighting analytics
  src/app/content/highlights/components/Confirmation.tsx
  src/app/content/highlights/components/DisplayNote.tsx
  src/app/content/highlights/components/EditCard.spec.tsx
  src/app/content/highlights/components/EditCard.tsx
  src/helpers/analytics.ts
  src/helpers/analyticsEvents/highlighting/createNote.ts
  src/helpers/analyticsEvents/highlighting/editColor.ts
  src/helpers/analyticsEvents/highlighting/editNote.ts
Labels: WIP

#474 chore: stabilize screenshots by removing interesting content
  src/app/content/__image_snapshots__/content-screenshotspec-ts-content-looks-right-1-snap.png
  src/app/content/content.screenshotspec.ts
Labels: kd-maint
