Repository openstax/rex-web, pull requests merged in 2020-02, with the labels that each got.

#480 include missing packages to req
  pytest-selenium/requirements-dev.txt
Labels: bug

#408 Initial Highlight editing in SummaryPopup
  src/app/components/Dropdown.spec.tsx
  src/app/components/Dropdown.tsx
  src/app/components/Loader.tsx
  src/app/content/components/CallToActionPopup/styles.tsx
  src/app/content/highlights/components/Card.spec.tsx
  src/app/content/highlights/components/CardWrapper.tsx
  src/app/content/highlights/components/ColorPicker.spec.tsx
  src/app/content/highlights/components/ColorPicker.tsx
  src/app/content/highlights/components/DisplayNote.tsx
  src/app/content/highlights/components/Highlights.spec.tsx
  src/app/content/highlights/components/Highlights.tsx
  src/app/content/highlights/components/MenuToggle.tsx
  src/app/content/highlights/components/Note.tsx
  src/app/content/highlights/components/ShowMyHighlights.spec.tsx
  src/app/content/highlights/components/ShowMyHighlights.tsx
  src/app/content/highlights/components/ShowMyHighlightsStyles.tsx
  src/app/content/highlights/components/SummaryPopup/ContextMenu.spec.tsx
  src/app/content/highlights/components/SummaryPopup/ContextMenu.tsx
  src/app/content/highlights/components/SummaryPopup/FiltersList.tsx
  src/app/content/highlights/components/SummaryPopup/HighlightAnnotation.spec.tsx
  src/app/content/highlights/components/SummaryPopup/HighlightAnnotation.tsx
  src/app/content/highlights/components/SummaryPopup/HighlightDeleteWrapper.spec.tsx
  src/app/content/highlights/components/SummaryPopup/HighlightDeleteWrapper.tsx
  src/app/content/highlights/components/SummaryPopup/HighlightListElement.tsx
  src/app/content/highlights/components/SummaryPopup/__snapshots__/ContextMenu.spec.tsx.snap
  src/app/content/highlights/components/SummaryPopup/__snapshots__/HighlightAnnotation.spec.tsx.snap
  src/app/content/highlights/components/SummaryPopup/__snapshots__/HighlightDeleteWrapper.spec.tsx.snap
  src/app/content/highlights/components/SummaryPopup/styles.ts
  src/app/content/highlights/components/__snapshots__/ColorPicker.spec.tsx.snap
  src/app/content/highlights/components/__snapshots__/DisplayNote.spec.tsx.snap
  src/app/content/highlights/reducer.ts
  src/app/content/highlights/utils/index.ts
  src/app/content/highlights/utils/summaryHighlightsUtils.spec.ts
  src/app/content/highlights/utils/summaryHighlightsUtils.ts
  src/app/domUtils.spec.ts
  src/app/domUtils.ts
  src/app/guards.ts
  src/app/messages/en/messages.json
  src/app/reactUtils.spec.tsx
  src/app/reactUtils.ts
  src/typings/global.d.ts
Labels: change

#517 [WIP] Add some tests for pr issue-589
  src/app/content/highlights/components/Highlights.spec.tsx
  src/app/content/highlights/components/ShowMyHighlights.spec.tsx
  src/app/content/highlights/components/SummaryPopup/ContextMenu.spec.tsx
  src/app/content/highlights/components/SummaryPopup/__snapshots__/ContextMenu.spec.tsx.snap
  src/test/mocks/highlightData.ts
Labels: WIP
